name = "winter-cherry-2261"
main = "worker.js"
compatibility_date = "2024-01-01"

# Environment variables (stored as secrets in Cloudflare)
# Set these using: wrangler secret put GITHUB_CLIENT_ID
# wrangler secret put GITHUB_CLIENT_SECRET
# wrangler secret put GITHUB_REDIRECT_URI

[env.production]
name = "winter-cherry-2261"

# You can add other environments like staging if needed
# [env.staging]
# name = "winter-cherry-2261-staging"
